{{- if .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "akka-cluster.fullname" . }}
  labels:
    {{- include "akka-cluster.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "watch", "list"]
{{- end }}