{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "akka-cluster.fullname" . }}
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "akka-cluster.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "akka-cluster.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}