{{- if .Values.akka.management.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "akka-cluster.fullname" . }}-management
  labels:
    {{- include "akka-cluster.labels" . | nindent 4 }}
    {{- with .Values.akka.management.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.akka.management.annotations | nindent 4 }}
spec:
  type: {{ .Values.akka.management.type }}
  ports:
    - port: {{ .Values.akka.management.port }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "akka-cluster.selectorLabels" . | nindent 4 }}
{{- end }}